set(EMLIB_ARCH "armv7em")
set(EMLIB_ABI "eabihf")
if(EMLIB_ARCH_FLAGS)
	if(EMLIB_ARCH_FLAGS MATCHES "^-mfpu=([^ ]+)$")
		set(EMLIB_ARCH_FLAGS "-march=armv7em -mfloat-abi=hard ${EMLIB_ARCH_FLAGS}")
		set(preset_hash "armv7em-hard-${CMAKE_MATCH_1}")
	else()
		message(FATAL_ERROR "EMLIB_ARCH_FLAGS for preset 'thumbv7em-none-eabihf' can set '-mfpu=...' only")
	endif()
else()
	set(EMLIB_ARCH_FLAGS "-march=armv7em -mfloat-abi=hard -mfpu=fpv4-sp-d16")
	set(preset_hash "armv7em-hard-fpv4-sp-d16")
endif(EMLIB_ARCH_FLAGS)

include("cmake/arm.cmake")
