set(EMLIB_ARCH "armv8m.main")
set(EMLIB_ABI "eabihf")
if(EMLIB_ARCH_FLAGS)
	if(EMLIB_ARCH_FLAGS MATCHES "^-mfpu=([^ ]+)$")
		set(EMLIB_ARCH_FLAGS "-march=armv8m.main -mfloat-abi=hard ${EMLIB_ARCH_FLAGS}")
		set(preset_hash "armv8m.main-hard-${CMAKE_MATCH_1}")
	else()
		message(FATAL_ERROR "EMLIB_ARCH_FLAGS for preset 'thumbv8m.main-none-eabihf' can set '-mfpu=...' only")
	endif()
else()
	set(EMLIB_ARCH_FLAGS "-march=armv8m.main -mfloat-abi=hard -mfpu=fpv5-sp-d16")
	set(preset_hash "armv8m.main-hard-fpv5-sp-d16")
endif(EMLIB_ARCH_FLAGS)

include("cmake/arm.cmake")
