set(EMLIB_ARCH "armv8m.main")
set(EMLIB_ABI "eabi")
if(EMLIB_ARCH_FLAGS)
	if(EMLIB_ARCH_FLAGS MATCHES "^-mfpu=([^ ]+)$")
		if(CMAKE_MATCH_1 STREQUAL "none")
			set(float_abi soft)
		else()
			set(float_abi softfp)
		endif()
		set(EMLIB_ARCH_FLAGS "-march=armv8m.main -mfloat-abi=${float_abi} ${EMLIB_ARCH_FLAGS}")
		set(preset_hash "armv8m.main-${float_abi}-${CMAKE_MATCH_1}")
	else()
		message(FATAL_ERROR "EMLIB_ARCH_FLAGS for preset 'thumbv8m.main-none-eabi' can set '-mfpu=...' only")
	endif()
else()
	set(EMLIB_ARCH_FLAGS "-march=armv8m.main -mfloat-abi=softfp -mfpu=fpv5-sp-d16")
	set(preset_hash "armv8m.main-softfp-fpv5-sp-d16")
endif(EMLIB_ARCH_FLAGS)

include("cmake/arm.cmake")
