set(EMLIB_ARCH "armv7em")
set(EMLIB_ABI "eabi")
if(EMLIB_ARCH_FLAGS)
	if(EMLIB_ARCH_FLAGS MATCHES "^-mfpu=([^ ]+)$")
		if(CMAKE_MATCH_1 STREQUAL "none")
			set(float_abi soft)
		else()
			set(float_abi softfp)
		endif()
		set(EMLIB_ARCH_FLAGS "-march=armv7em -mfloat-abi=${float_abi} ${EMLIB_ARCH_FLAGS}")
		set(preset_hash "armv7em-${float_abi}-${CMAKE_MATCH_1}")
	else()
		message(FATAL_ERROR "EMLIB_ARCH_FLAGS for preset 'thumbv7em-none-eabi' can set '-mfpu=...' only")
	endif()
else()
	set(EMLIB_ARCH_FLAGS "-march=armv7em -mfloat-abi=softfp -mfpu=fpv4-sp-d16")
	set(preset_hash "armv7em-softfp-fpv4-sp-d16")
endif(EMLIB_ARCH_FLAGS)

include("cmake/arm.cmake")
